export EDITOR='code'

alias kittyconfig='$EDITOR ~/.config/kitty/kitty.conf'
alias zshconfig='$EDITOR ~/Documents/MBP/programming/vscode/zshconfig.code-workspace'
alias i3config='$EDITOR ~/.config/i3/config'
alias vimconfig='$EDITOR ~/.vimrc'
alias polybarconfig='$EDITOR ~/.config/polybar/config'
alias yabaiconfig='$EDITOR ~/.config/yabai/yabairc'
alias skhdconfig='$EDITOR ~/.config/skhd/skhdrc'
alias spacebarconfig='$EDITOR ~/.config/spacebar/spacebarrc'
alias mtmrconfig='code ~/.config/mtmr/items.json'
alias nvimconfig='$EDITOR ~/.config/nvim/init.vim'