bookmark_prefix="ff"
documents_folder="/Users/sam/Documents/MBP"
export ${bookmark_prefix}d="${documents_folder}"
export ${bookmark_prefix}n="${documents_folder}/notes"
export ${bookmark_prefix}D="${HOME}/Downloads"
export ${bookmark_prefix}t="/Volumes/local_media/tv-shows"